### ISSUE TITLE
BEEP BEEP BEEP for every keypress and BEL hangs!

### ISSUE THREAD

**Issue by piterpunk** [ducasp/MSX-Development#24]
The title says everything.

The TELNET code is BEEPing (printChar(7)) for every keypress and it is very annoying.

And when msx2ansi receives BEL, it calls BEEP and hangs.

So we are having a lot of beeps when not called and no beep (and no work at al) when called.

Fix is available in #23

**Comment by ducasp** [comment]
Tks, I've forgot to take out the beeping, did that to test reliability and it seems did not work lol 

Tks again for another great contribution :)
