### ISSUE TITLE
tniASM v0.45 distribution

### ISSUE THREAD

**Issue by BiFiMSX** [ducasp/MSX-Development#28]
Hi,

I would like to inform you that tniASM v0.45 is to be distributed with the manual or not at all. As an alternative you can always point to the tniASM product website on http://www.tni.nl/products/tniasm.html

tniASM v0.45 is freeware and can be distributed freely as long it is not modified, the manual is in the archive and it is not part of a commercial product.

On behalf of The New Image, we thank you for chosing tniASM for your developments and we hope this will be corrected.

**Comment by ducasp** [comment]
Thanks for the heads up, should have been fixed, please let me know if
there are any other issues. 🙂

Em dom, 26 de abr de 2020 15:43, BiFi <notifications@github.com> escreveu:
