### ISSUE TITLE
TELNET client printing unknown escape codes on screen

### ISSUE THREAD

**Issue by cmilanf** [ducasp/MSX-Development#34]
New Synchronet BBS versions are sending xterm escape sequences to allow mouse input in the BBS. These are of no use on MSX and they should be ignored, as any unknown escape sequence. As the sequence is not ignored, each time the BBS request input to the user, `1000h1006h` is shown.

The offending codes are the following ones:
```
ESC [?1000h
ESC [?1006h
```

I am attaching a network payload dump of a connection to the BBS showing the codes:

```
0000   10 7b 44 52 ff a9 00 15 5d 12 0b 2d 08 00 45 00   .{DR....]..-..E.
0010   00 e3 dd 60 40 00 40 06 b6 b2 c0 a8 12 05 c0 a8   ...`@.@.........
0020   12 ac 00 17 f7 3a ba 7d 87 2e 74 02 9c ff 50 18   .....:.}..t...P.
0030   01 f6 3d 36 00 00 2e 20 53 69 20 74 75 20 63 6c   ..=6... Si tu cl
0040   69 65 6e 74 65 20 54 45 4c 4e 45 54 2f 53 53 48   iente TELNET/SSH
0050   20 73 6f 70 6f 72 74 61 0d 0a 65 73 74 61 20 63    soporta..esta c
0060   6f 64 69 66 69 63 61 63 69 6f 6e 2c 20 70 75 65   odificacion, pue
0070   64 65 73 20 70 72 6f 62 61 72 20 61 20 61 63 74   des probar a act
0080   69 76 61 72 6c 61 2e 20 44 69 73 63 75 6c 70 61   ivarla. Disculpa
0090   20 6c 61 73 20 6d 6f 6c 65 73 74 69 61 73 2e 0d    las molestias..
00a0   0a 1b 5b 33 32 6d 0d 0a 45 6e 74 65 72 20 6e 75   ..[32m..Enter nu
00b0   6d 62 65 72 20 6f 66 20 62 75 6c 6c 65 74 69 6e   mber of bulletin
00c0   20 6f 72 20 5b 1b 5b 31 3b 33 37 6d 1b 5b 3f 31    or [.[1;37m.[?1
00d0   30 30 30 68 1b 5b 3f 31 30 30 36 68 51 1b 5b 30   000h.[?1006hQ.[0
00e0   3b 33 32 6d 75 69 74 5d 3a 20 1b 5b 31 3b 33 37   ;32muit]: .[1;37
00f0   6d                                                m
```

Could you make the client ignore any unknown escape sequences?

**Comment by ducasp** [comment]
Hi Karloch,

This is quite unfortunate position from Syncrhonet team as those are absolutely not part of the ANSI standard codes, those are xterm escape sequences that are structured like ANSI commands. They should not send XTERM commands to a terminal that replied its capabilities as ANSI, it makes no sense. 

The behavior of hidding unknow escape sequences is not mandatory, and, many ANSI compliant terminals have the behavior of showing unknown escape sequences, just so both users and administrators might be aware of unexpected errors. And for an ANSI terminal this is absolutely an unkown escape sequence.

It is a very lazy and confortable position of Synchronet team to tell that terminal is wrong. It is not. So this is not an issue in the Telnet terminal.

**Comment by ducasp** [comment]
On the other hand, I've already worked on a version of the ANSI MSX2 library that will not show unknow escape sequences that have up to 5 digits parameters, it should be part of the next Telnet release and it will work around Synchronet BBS bug of sending XTERM sequences to a terminal that has clearly been negotiated as an ANSI type terminal.

**Comment by cmilanf** [comment]
Indeed you have your point, and it looks like there is nothing I can do about the Synchronet dev team decission.

I think it is worth to mention, that I tried connection to the HispaMSX using the telnet clients included in Windows and GNU/Linux (BSD telnet client) and they do not show these unknown escape codes. I would be very surprised if the Windows one has any knowledge about xterm :)

**Comment by ducasp** [comment]
> Indeed you have your point, and it looks like there is nothing I can do about the Synchronet dev team decission.
> 
> I think it is worth to mention, that I tried connection to the HispaMSX using the telnet clients included in Windows and GNU/Linux (BSD telnet client) and they do not show these unknown escape codes. I would be very surprised if the Windows one has any knowledge about xterm :)

Yeah, Windows Telnet Client does implement quite a few VT and XTERM commands, not all, and choose to not show unknown escape sequences, if you are using Windows 10, then it has quite a few XTERM commands supported as they are trying to make it really Linux friendly. Linux uses XTERM, so its terminal implement most (if not all) VT commands and have all XTERM xtensions, so it  is in fact executing the code. MSX2ANSI also implement a few of those that are not ANSI, as well as SyncTerm implement a lot more (including the mouse related escape codes).

We will get a work around (it is done in fact, just that I'm looking at other fixes before releasing the next version of Telnet), it just irks me out when a lazy development team do not want to take blame when they do things that are not standard.

**Comment by ducasp** [comment]
Sorry for leaving this issue "un-attended" for so long... I had made a change in the ANSI library to fix it and already tested (worked fine), wanted to release along with some other new features on Telnet but my daily work charge just increased quite a bit in the past months. So, I plan to release a new Telnet with it fixed in a couple days, even if I can't get more features into it. :)

**Comment by cmilanf** [comment]
No hurries, it is not like the client is broken or doesn't work. It's just an annoying visual thing I can live with until fixed :)

Thanks for the update!
